### ISSUE TITLE
Get an error when running ecto.create

### ISSUE THREAD

**Issue by sebastialonso** [rbeene/phoenix-with-docker#4]
Just following all the instructions in the README.
The error:

~~~
** (UndefinedFunctionError) function Mix.Project.apps_paths/0 is undefined or private. Did you mean one of:

      * app_path/0
      * app_path/1
      * deps_path/0
      * deps_path/1
      * deps_paths/0

    (mix) Mix.Project.apps_paths()
    lib/mix/ecto.ex:25: Mix.Ecto.parse_repo/2
    lib/mix/tasks/ecto.create.ex:33: Mix.Tasks.Ecto.Create.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

~~~

What is happening behind the scenes? Is this an Elixir version issue?

**Comment by josborn-dish** [comment]
I get the same thing when I run "mix test".  My elixir version is 1.3.3 (I know, it's old--reviving old project, long story) and Erlang 18.3.
